server:
  port: 8080

spring:
  application:
    name: brickers-api

  config:
    import: "optional:file:.env[.properties]"

  data:
    data:
      mongodb:
        host: ${MONGO_HOST}    
        port: ${MONGO_PORT}      
        database: ${MONGO_DB_NAME} 
        username: ${MONGO_USER}   
        password: ${MONGO_PASSWORD}
        
  mongodb:
    uri: ${PRIMARY_MONGODB_URI}
    auto-index-creation: true
    

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "${LOCAL_BASE_URL:http://localhost:8080}/auth/google/callback"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "${LOCAL_BASE_URL:http://localhost:8080}/auth/kakao/callback"
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  front-base-url: ${FRONT_BASE_URL:http://localhost:5173}
  cookie:
    secure: ${COOKIE_SECURE:false}   # 로컬은 false, 배포는 true
    same-site: ${COOKIE_SAMESITE:Lax} # 로컬 Lax, 배포 None
  
# ✅ 업로드 설정
  upload:
    provider: S3
    public-base-url: ${UPLOAD_PUBLIC_BASE_URL:https://YOUR_BUCKET.s3.ap-northeast-2.amazonaws.com} # 또는 CloudFront 도메인
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_REGION:ap-northeast-2}
      presign-exp-seconds: ${AWS_PRESIGN_EXP_SECONDS:120}
      key-prefix: ${AWS_S3_KEY_PREFIX:uploads}   # uploads/{userId}/yyyy/MM/{uuid}.png
      max-bytes: ${UPLOAD_MAX_BYTES:10485760}     # 10MB
      allowed-content-types: image/png,image/jpeg,image/webp


jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    "[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG
    "[org.springframework.data.mongodb.core.index]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": DEBUG

springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json