server:
  port: 8080

spring:
  application:
    name: brickers-api

  config:
    import: "optional:file:.env[.properties]"

  data:
    data:
      mongodb:
        host: ${MONGO_HOST}    
        port: ${MONGO_PORT}      
        database: ${MONGO_DB_NAME} 
        username: ${MONGO_USER}   
        password: ${MONGO_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "${LOCAL_BASE_URL:http://localhost:8080}/auth/google/callback"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "${LOCAL_BASE_URL:http://localhost:8080}/auth/kakao/callback"
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  front-base-url: ${FRONT_BASE_URL:http://localhost:5173}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    "[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG
